In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

: 

You should consider upgrading via the 'C:\Users\Yashvi\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [3]:
pip install -U scikit-learn scipy matplotlib

You should consider upgrading via the 'C:\Users\Yashvi\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [4]:
!pip install scikit-learn scipy matplotlib numpy

You should consider upgrading via the 'C:\Users\Yashvi\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [6]:
data=pd.read_csv('final_dataset.csv')

In [7]:
data

GRE Score  TOEFL Score  University Rating  LOR   CGPA  Work Experience  \
0          337          118                  4   4.5  9.65                1   
1          324          107                  4   4.5  8.87                1   
2          316          104                  3   3.5  8.00                1   
3          322          110                  3   2.5  8.67                1   
4          314          103                  2   3.0  8.21                0   
..         ...          ...                ...   ...   ...              ...   
395        324          110                  3   3.5  9.04                1   
396        325          107                  3   3.5  9.11                1   
397        330          116                  4   4.5  9.45                1   
398        312          103                  3   4.0  8.78                0   
399        333          117                  4   4.0  9.66                1   

     Probability of eligibility  
0                          0.92  
1                          0.76  
2                          0.72  
3                          0.80  
4                          0.65  
..                          ...  
395                        0.82  
396                        0.84  
397                        0.91  
398                        0.67  
399                        0.95  

[400 rows x 7 columns]

In [8]:
y=data[['Probability of Eligibility']].values
x=data.drop(['Probability of Eligibility'], axis=1).values

KeyError: "None of [Index(['Probability of Eligibility'], dtype='object')] are in the [columns]"

In [9]:
y=data[['Probability of eligibility']].values
x=data.drop(['Probability of eligibility'], axis=1).values

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [11]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [12]:
y_predict=lr.predict(x_test)
y_predict
y_test

array([[0.61],
       [0.81],
       [0.89],
       [0.57],
       [0.93],
       [0.64],
       [0.97],
       [0.64],
       [0.89],
       [0.34],
       [0.58],
       [0.78],
       [0.82],
       [0.65],
       [0.91],
       [0.66],
       [0.88],
       [0.7 ],
       [0.78],
       [0.45],
       [0.49],
       [0.79],
       [0.46],
       [0.67],
       [0.57],
       [0.62],
       [0.88],
       [0.81],
       [0.54],
       [0.64],
       [0.7 ],
       [0.96],
       [0.9 ],
       [0.56],
       [0.62],
       [0.84],
       [0.7 ],
       [0.93],
       [0.83],
       [0.97],
       [0.72],
       [0.61],
       [0.85],
       [0.74],
       [0.86],
       [0.94],
       [0.75],
       [0.59],
       [0.78],
       [0.72],
       [0.74],
       [0.7 ],
       [0.71],
       [0.8 ],
       [0.72],
       [0.91],
       [0.76],
       [0.73],
       [0.69],
       [0.76],
       [0.86],
       [0.52],
       [0.6 ],
       [0.47],
       [0.95],
       [0.71],
       [0.

In [13]:
y_predict

array([[0.55993359],
       [0.80068512],
       [0.90432778],
       [0.69457567],
       [0.89885992],
       [0.65535133],
       [0.99062565],
       [0.55192586],
       [0.85433579],
       [0.47566459],
       [0.58538817],
       [0.6987553 ],
       [0.8077855 ],
       [0.60049196],
       [0.85920634],
       [0.66654792],
       [0.85892295],
       [0.77888533],
       [0.73618519],
       [0.71977918],
       [0.47513663],
       [0.80428261],
       [0.6459838 ],
       [0.60750925],
       [0.65762356],
       [0.64932595],
       [0.85851677],
       [0.73578612],
       [0.64971629],
       [0.5824296 ],
       [0.70115143],
       [0.96093579],
       [0.88036486],
       [0.66709225],
       [0.65195256],
       [0.81407831],
       [0.68130611],
       [0.90392928],
       [0.84541409],
       [0.98312895],
       [0.72932165],
       [0.65520226],
       [0.83591157],
       [0.67572616],
       [0.83231639],
       [0.95034415],
       [0.72519635],
       [0.619

In [14]:
y_test

array([[0.61],
       [0.81],
       [0.89],
       [0.57],
       [0.93],
       [0.64],
       [0.97],
       [0.64],
       [0.89],
       [0.34],
       [0.58],
       [0.78],
       [0.82],
       [0.65],
       [0.91],
       [0.66],
       [0.88],
       [0.7 ],
       [0.78],
       [0.45],
       [0.49],
       [0.79],
       [0.46],
       [0.67],
       [0.57],
       [0.62],
       [0.88],
       [0.81],
       [0.54],
       [0.64],
       [0.7 ],
       [0.96],
       [0.9 ],
       [0.56],
       [0.62],
       [0.84],
       [0.7 ],
       [0.93],
       [0.83],
       [0.97],
       [0.72],
       [0.61],
       [0.85],
       [0.74],
       [0.86],
       [0.94],
       [0.75],
       [0.59],
       [0.78],
       [0.72],
       [0.74],
       [0.7 ],
       [0.71],
       [0.8 ],
       [0.72],
       [0.91],
       [0.76],
       [0.73],
       [0.69],
       [0.76],
       [0.86],
       [0.52],
       [0.6 ],
       [0.47],
       [0.95],
       [0.71],
       [0.

In [15]:
y_predict

array([[0.55993359],
       [0.80068512],
       [0.90432778],
       [0.69457567],
       [0.89885992],
       [0.65535133],
       [0.99062565],
       [0.55192586],
       [0.85433579],
       [0.47566459],
       [0.58538817],
       [0.6987553 ],
       [0.8077855 ],
       [0.60049196],
       [0.85920634],
       [0.66654792],
       [0.85892295],
       [0.77888533],
       [0.73618519],
       [0.71977918],
       [0.47513663],
       [0.80428261],
       [0.6459838 ],
       [0.60750925],
       [0.65762356],
       [0.64932595],
       [0.85851677],
       [0.73578612],
       [0.64971629],
       [0.5824296 ],
       [0.70115143],
       [0.96093579],
       [0.88036486],
       [0.66709225],
       [0.65195256],
       [0.81407831],
       [0.68130611],
       [0.90392928],
       [0.84541409],
       [0.98312895],
       [0.72932165],
       [0.65520226],
       [0.83591157],
       [0.67572616],
       [0.83231639],
       [0.95034415],
       [0.72519635],
       [0.619

In [23]:
import pickle

In [25]:
with open('model_pickel','wb') as f:
    pickle.dump(lr,f)

In [31]:
with open('model_pickel','rb') as f:
    mp=pickle.load(f)

with open('model_pickel','rb') as f:
    mp=pickle.load(f)

In [35]:
mp.predict(0.81)

ValueError: Expected 2D array, got scalar array instead:
array=0.81.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [36]:
array.reshape(-1, 1)

NameError: name 'array' is not defined